### ISSUE TITLE
hitomi crash

### ISSUE THREAD

**Issue by yant0** [Nonononoki/Hendroid#51]
**Hendroid Version**: 1.15.15

**Device/Android Version**:

**Issue details / Repro steps**: open hitomi

**Stack trace / LogCat**:
```latest-crash log : begin
Hentoid ver: 1.15.15 (188)
API: 29
Device: ASUS_X00TDA
Start : 2022-01-11T01:40:25.999Z
End : 2022-01-11T01:40:25.999Z (00:00)
-----
Error in {min,max} interval near index 72
^https://ltn\.hitomi\.la/tuf41b/sz5yk08pugnbugrqk-11-2048569\.js?yuo1={%22objname%22:%22uikphz4lcpl%22,%22request_id%22:0,%22zones%22:[{%22idzone%22:%222048569%22,%22here%22:{}}]}$
                                                                        ^
java.util.regex.PatternSyntaxException: Error in {min,max} interval near index 72
^https://ltn\.hitomi\.la/tuf41b/sz5yk08pugnbugrqk-11-2048569\.js?yuo1={%22objname%22:%22uikphz4lcpl%22,%22request_id%22:0,%22zones%22:[{%22idzone%22:%222048569%22,%22here%22:{}}]}$
                                                                        ^
	at java.util.regex.Pattern.compileImpl(Native Method)
	at java.util.regex.Pattern.compile(Pattern.java:1433)
	at java.util.regex.Pattern.<init>(Pattern.java:1408)
	at java.util.regex.Pattern.compile(Pattern.java:966)
	at me.devsaki.hentoid.util.AdBlocker.addJsUrlPatternWhitelist(AdBlocker.java:138)
	at me.devsaki.hentoid.util.AdBlocker.isBlocked(AdBlocker.java:201)
	at me.devsaki.hentoid.activities.sources.CustomWebViewClient.shouldInterceptRequestInternal(CustomWebViewClient.java:383)
	at me.devsaki.hentoid.activities.sources.CustomWebViewClient.shouldInterceptRequest(CustomWebViewClient.java:367)
	at me.devsaki.hentoid.activities.sources.HitomiActivity$HitomiWebClient.shouldInterceptRequest(HitomiActivity.java:135)
	at A7.a(chromium-SystemWebView.apk-default-447216403:15)
	at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(chromium-SystemWebView.apk-default-447216403:2)

latest-crash log : end
```

**Comment by Nonononoki** [comment]
Use latest vervion: https://github.com/Nonononoki/Hendroid/releases/tag/1.15.17

**Comment by yant0** [comment]
forgot fdroid is always late on updates, will do just that
